fix: log error & remove deprecated linter
moonD4rk/HackBrowserData pull request #171
Opened 2022-10-21 07:26 UTC by carr0t2

Such as input the wrong command line parameters
The original error will be panic since log is not init.
![image](https://user-images.githubusercontent.com/62796978/197137194-c3c2d049-15dd-4a45-9829-98a67d9d8417.png)
After fix.
![image](https://user-images.githubusercontent.com/62796978/197137616-1c080893-d956-45ed-9edb-319818cd2101.png)

2022-10-23 17:12 UTC, carr0t2 commented
The linter 'varcheck' 'deadcode' 'structcheck' is deprecated (since v1.49.0), use 'unused' instead.

2022-10-24 03:10 UTC, moonD4rk commented
> The linter 'varcheck' 'deadcode' 'structcheck' is deprecated (since v1.49.0), use 'unused' instead.

THX, I will remove this lint, you could revert lint commit~

2022-10-24 04:56 UTC, moonD4rk requested changes
revert golangci config file, and change log to `Println` and `os.Exit`, Thx

2022-10-24 04:56 UTC, moonD4rk commented on cmd/hack-browser-data/main.go
> +		log.Init("debug")
use `log.Fatal` is better, and reference from [log.Fatal](https://pkg.go.dev/log#Fatal), `Print()` and `os.exit` is enough
> Fatal is equivalent to Print() followed by a call to os.Exit(1).
> ```
> // Fatal is equivalent to Print() followed by a call to os.Exit(1).
> func Fatal(v ...any) {
> 	std.Output(2, fmt.Sprint(v...))
> 	os.Exit(1)
> }
> ```
so, just use this. ↓

``` go
fmt.Println(err)
os.exit(1)
```

2022-10-24 06:05 UTC, moonD4rk approved these changes

2022-10-24 06:18 UTC, moonD4rk commented on cmd/hack-browser-data/main.go
> +		log.Init("debug")
This is better, so i changed your code and merge to master


```go
import (
	glog "log"
)
func main() {
	glog.fatal(err)
}
```

2022-10-24 06:20 UTC, merged